# Generated by Django 4.0.4 on 2022-05-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hocsinh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('maLopHoc', models.AutoField(primary_key=True, serialize=False)),
                ('tenLopHoc', models.CharField(default='', max_length=100)),
                ('moTa', models.CharField(default='', max_length=255)),
                ('siSoLop', models.IntegerField()),
                ('namHoc', models.IntegerField()),
                ('maGVCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc_HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocsinh.hocsinh')),
                ('maLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lophoc.lophoc')),
            ],
        ),
    ]
