# Generated by Django 4.0.4 on 2022-05-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('maHocSinh', models.AutoField(primary_key=True, serialize=False)),
                ('hoTen', models.CharField(default='', max_length=100)),
                ('diaChi', models.CharField(default='', max_length=255)),
                ('dob', models.DateField()),
                ('phoneNumber', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=255)),
                ('gioiTinh', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XepLoai',
            fields=[
                ('maXepLoai', models.AutoField(primary_key=True, serialize=False)),
                ('diemTongKet', models.IntegerField()),
                ('hanhKiem', models.CharField(default='', max_length=50)),
                ('xepLoai', models.CharField(default='', max_length=50)),
                ('lopHoc', models.IntegerField()),
                ('maHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocsinh.hocsinh')),
            ],
        ),
    ]
