# Generated by Django 4.0.4 on 2022-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocsinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocsinh',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='gioiTinh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
