# Generated by Django 4.0.4 on 2022-05-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hocsinh', '__first__'),
        ('monhoc', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiKiemTra',
            fields=[
                ('maLoaiBaiKiemTra', models.AutoField(primary_key=True, serialize=False)),
                ('tenLoaiBaiKiemTra', models.CharField(default='', max_length=100)),
                ('moTa', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kiemtra',
            fields=[
                ('maBaiKiemTra', models.AutoField(primary_key=True, serialize=False)),
                ('tenBaiKiemTra', models.CharField(default='', max_length=50)),
                ('ngayLamBaiKiemTra', models.DateField()),
                ('maLoaiBaiKiemTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diemkiemtra.loaikiemtra')),
            ],
        ),
        migrations.CreateModel(
            name='KetQua_KiemTra',
            fields=[
                ('maKetQua_KiemTra', models.AutoField(primary_key=True, serialize=False)),
                ('soDiem', models.IntegerField()),
                ('maBaiKiemTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diemkiemtra.kiemtra')),
                ('maHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocsinh.hocsinh')),
                ('maMonHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhoc.monhoc')),
            ],
        ),
    ]
